pluginManagement {
    repositories {
        gradlePluginPortal()
        maven {
            name = 'MinecraftForge'
            url = 'https://maven.minecraftforge.net/'
        }
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '0.7.0'
}

rootProject.name = 'axion-engine'

// Arborescence figee par la PARTIE 33 du cahier des charges : les modules Java
// vivent sous java/, les crates Rust sous crates/.
include ':axion-api'
project(':axion-api').projectDir = file('java/axion-api')

include ':axion-mod'
project(':axion-mod').projectDir = file('java/axion-mod')
